import React from 'react';
import "./style.css";
const TermsAndCondition = () => {

return(
    <div className='custom_terms container pt-4'>
    <h1 className='terms_heading'>Website Terms & Conditions</h1>
    <p>Welcome to www.katelstewart.com.  Kate L. Stewart and/or her affiliates, partners, and assigns, ("KS") provides website features to you subject to the following Terms and Conditions ("Terms and Conditions”).  The Terms and Conditions govern your use of the World Wide Web site located at www.katelstewart.com, and any associated subpages ("Site").  By accessing, viewing, or using the content, material, or services available on or through this Site, you indicate that you have read and understand these Terms and Conditions, and that you agree to them and intend to be legally bound by them. If you do not agree to these Terms and Conditions, you are not granted permission to use this Site and must exit immediately.
These Terms and Conditions may be changed at any time.  It is your obligation as a user visiting the Site to familiarize yourself with these Terms and Conditions.  Any change to these Terms and Conditions shall also be effective as to any visitor who has visited the Site before the change was made.</p>
<h4>1. Website Information</h4>
<p>If you are seeking medical attention or if you feel that you may be a danger to yourself or others, please call 911 immediately.</p>
   <p>KS attempts to be as accurate as possible.  However, KS does not warrant that information or other content of this Site is accurate, complete, reliable, current, or error-free.  The specific application of information and principles on this Site will vary according to the particular circumstances of each individual.</p>
    <p>This Site, and its entire content, is offered by KS for informational purposes only, and is in no way intended to constitute medical or psychological diagnosis or treatment of any kind.  Your use of this Site, including for the purpose of communicating with KS, does not create a psychotherapist/client relationship, nor legal privilege.  You should not act upon any information provided on this Site without first seeking individual professional advice.</p>
    <h4>2. Proprietary Rights</h4>
    <h5>LICENSE AND SITE ACCESS</h5>  
    <p>KS grants you a limited license to access and make personal use of this Site, and expressly does not grant a license to download (other than page caching) or modify the Site, or any portion of it, except with express written consent of KS.  This license does not include any resale or commercial use of this Site or its contents; any collection and use of any product or service listings, descriptions, or prices; any derivative use of this Site or its contents; any downloading or copying of account information for the benefit of another business or enterprise; or any use of data mining, robots, or similar data gathering and extraction tools.  This Site or any portion of this Site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of KS.  You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of KS without express written consent.  You may not use any meta tags or any other "hidden text" utilizing KS’s name or trademarks without the express written consent of KS.  Any unauthorized use immediately terminates the permission or license granted by KS.  You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the home page of katelstewart.com so long as the link does not portray KS, or the associated products or services in a false, misleading, derogatory, or otherwise offensive manner.  You may not use KS’s logos or other proprietary graphic or trademark as part of the link without the express written permission of KS.</p> 
    <h5>LICENSE AND SITE ACCESS</h5> 
    <p>All content included on this Site, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software, is the property of KS or her content suppliers and protected by United States and international copyright laws.  The compilation of all content on this Site is the exclusive property of KS and is protected by U.S. and international copyright laws.  All software used on this Site is the property of KS or the relevant software suppliers and protected by United States and international copyright laws.</p> 
   <p>All works of authorship, information, content, and material appearing on or contained in this Site ("Site Materials") are protected by law, including but not limited to, United States copyright law.  Except as explicitly stated in the Site, the entirety of the Site Materials (including, without limitation, data, illustrations, graphics, audio, video, photographs, pictures, illustrations, recordings, drawings, sketches, artwork, images, text, forms, and look and feel attributes) are © 2011-2014 Kate L. Stewart, all rights reserved.  KS also owns a copyright in this Site as a collective work and/or compilation, and in the selection, coordination, arrangement, organization and enhancement of the Site Materials.</p>
   <p>Removing or altering any copyright notice or any other proprietary notice on any Site Materials is strictly prohibited.  Any commercial use of any or all Site Materials, in whole or in part, without the prior written consent of KS, is prohibited.  Any reproduction, distribution, performance, display, preparation of derivative works based upon, framing, capturing, harvesting, or collection of, or creating of hypertext or other links or connections to any Site Materials or any other proprietary information of KS, without KS's advance written consent, is prohibited.</p>
   <h5>TRADEMARKS </h5> 
   <p>All names, trademarks, service marks, symbols, slogans, and logos appearing on the Site are proprietary to KS or her licensors.  Use or misuse of these trademarks is expressly prohibited and may violate federal, state, and international trademark law.<br/><br/>
   Kate L. Stewart, MA, www.katelstewart.com, , and other Site graphics, logos, page headers, button icons, scripts, and service names are trademarks, registered trademarks or trade dress of KS in the U.S. and/or other countries.  KS’s trademarks and trade dress may not be used in connection with any product or service that is not KS’s, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits KS.  All other trademarks not owned by KS that appear on this Site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by KS.</p>
   <h4>3. Communications with and Submissions to the Site</h4>
    <h5>ELECTRONIC COMMUNICATIONS</h5>
    <p>This section is not intended to alter or amend any existing rules, laws, regulations, or standards regarding psychotherapist/client confidentiality or privilege.<br/><br/>KS encourages visitors to submit comments, and other content; send e-mail and other communications; and submit suggestions, ideas, questions, or other information (collectively, "Submissions"), so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, or other malware, commercial solicitation, chain letters, mass mailings, or any form of "spam."<br/><br/>When you visit the Site or transmit any Submissions to KS electronically, you are communicating with KS electronically.  By communicating with KS electronically, you consent to receive communications from KS electronically.  KS will communicate with you by e-mail or by posting notices on this Site.  By communicating with KS electronically, you also agree that all agreements, notices, disclosures and other communications that KS provides to you electronically satisfy any legal requirement that such communications be in writing.<br/><br/>By transmitting any submissions to KS electronically, you specifically acknowledge that you understand that KS makes no warranties or assurances that such submissions will be accessed, read, or responded to by KS.<br/><br/>KS has the right but not the obligation to monitor and edit or remove any activity or content posted to the Site.  KS takes no responsibility and assumes no liability for any content posted by you or any third party.<br/><br/></p>
   <p>By transmitting any Submission(s) to KS, you automatically grant KS, and any sublicensees, the royalty-free, perpetual, irrevocable, non-exclusive and fully sublicensable right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, redistribute, transmit, perform and display any or all of such Submissions (in whole or part) throughout the world and to incorporate such in other works and in any form, media, or technology now known or later developed for the full term of any rights that may exist in such Submission(s); and the right to use your name, likeness, voice, photograph, and any other indicia of identity and information provided to KS by you, in connection with the use, exploitation, promotion and/or advertising of the Submission(s) and/or the Site.  Further, KS is free to use any ideas, concepts, methods, techniques, and/or processes contained in any Submissions you send to this Site for any purpose whatever, including, but not limited to, creating and marketing products, information, or services using such information.<br/><br/>By transmitting any Submission(s) to KS, you hereby represent and warrant to KS that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify KS for all claims resulting from content you supply.<br/><br/></p>
   <p>By transmitting any Submission(s) to KS, you also represent and warrant that: (i) you are of legal age and otherwise legally competent to enter into contracts; (ii) you have all rights, approvals and/or consents necessary to submit the Submission(s) on the Terms provided herein; (iii) no permission is required from any other individual or company for KS to use the Submission(s); (iv) the materials contained in the Submission(s), including, without limitation, the, ideas, compositions, and other materials, are original, were created only by you, do not contain any "samples," excerpts, or other works from the material of others, and do not otherwise infringe on the intellectual property rights of any other individuals or companies; (v) the Submission(s) does not and will not violate any laws or be defamatory, libelous, pornographic or obscene; (vi) you are not bound by any contract that would prohibit you from agreeing to these Terms and Conditions; (vii) you will not hold KS liable for copyright or trademark infringement based, in whole or in part, upon KS's access to and use of the Submission(s); and (vi) the Submission(s) will not contain any "viruses" or other information that may damage or otherwise interfere with KS's computer systems or data, or the computer systems or data of users of KS's website.  You shall be fully responsible for any breach of the representations and warranties made to KS under this paragraph, and you shall indemnify KS and hold KS harmless from and against any and all claims, liabilities, actions, losses, damages and costs, including reasonable attorneys' fees and costs, arising from any such breach. <br/><br/>You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of an e-mail, posting or any other Submission.  KS maintains the right (but not the obligation) to review your Submission(s) and, in her sole discretion, decline to post and/or remove any Submission(s) for any reason or for no reason at all, at any time, with or without notice.</p>
    <p>You may request that KS delete your Submission(s) from the Site by emailing KS at info@katelstewart.com and specifically indentifying the Submission(s) you are requesting to be deleted.  Upon receipt of your emailed request, KS will make all reasonable efforts to delete your Submission(s) from the system and Site; however, KS disclaims any and all responsibility for any copies of your Submission(s) that may have been made by a user of the Site before your Submission(s) was removed.</p>
    <h4>4. Use and Nature of the Internet</h4> 
    <p>Given the nature of the internet, the transmission of any communication or Submission to KS via the Site or internet e-mail, whether encrypted or otherwise, cannot be guaranteed in all circumstances as secure.  As an alternative to communicating over the internet or e-mail, KS can be contacted by postal mail at: 2366 Eastlake Ave E. #402 Seattle, WA 98102.</p>
    <h4>5. Privacy</h4> 
    <p>KS has a Privacy Statement describing KS's online information gathering and dissemination practices with respect to the Site.  Please review the Privacy Statement, which is incorporated into these Terms and Conditions by reference, as if set forth fully herein, and which also governs your visit to the Site.  Additional information about your rights with respect to your private information is available in the HIPAA disclosure statement available at www.XXX.com or directly from KS.</p>
    <h4>6. Limitation of Liability & Disclaimer of Warranties and Conditions</h4> 
    <p>Use of the Internet is solely at your own risk and is subject to all applicable local, state, national, and international laws and regulations.  This Site, and all information, content, materials, products, and services included on and in or otherwise made available through this Site, are made available on an "as is," “as available,” and "with all faults" basis unless otherwise specified in writing.  You expressly agree that use of this Site is entirely at your own risk.<br/><br/>KS makes no representations or warranties of any kind, express or implied, as to the operation of this Site or the information, content, materials, products, or services included on or otherwise made available through this Site.<br/><br/>To the fullest extent permissible by applicable law, KS disclaims all representations, conditions, and warranties, with respect to this Site, the Site Materials on and in and made available through this Site, and the services, information, and products offered in connection therewith, express or implied, written or oral, arising from course of dealing, course of performance, usage of trade, or otherwise, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, accuracy, systems integration, non-interference, quality, title, and non-infringement.  The entire risk as to satisfactory quality, performance, accuracy, and effort with regard to any and all Site Materials on and in and made available through this Site is with you.</p>
   <p>KS shall not be liable for any direct, special, indirect, incidental, consequential, exemplary, extra-contractual, punitive, or other damages of any kind whatever, including, without limitation, lost revenues or lost profits, which may or do result from the use of, access to, or inability to use this Site, the Site Materials on and in and made available through this Site, or the services, information, and products offered in connection with this Site, regardless of legal theory, whether or not any party had been advised of the possibility or probability of such damages, and even if the remedies otherwise available fail of their essential purpose.  Under no circumstances will the total liability of KS to you or any other person or entity in connection with, based upon, or arising from this Site, the Site Materials on and in and made available through this Site, or the services, information, or products offered in connection therewith, exceed the price paid by you for use of this Site.<br/><br/>KS does not warrant that this Site, information, content, materials, products or services included on or otherwise made available to you through this Site, their servers, or e-mail sent from KS are free of viruses or other harmful components.</p>
   <h6>Typographical Errors</h6>
   <p>In the event that a KS product is mistakenly listed at an incorrect price, KS reserves the right to refuse or cancel any orders placed for product listed at the incorrect price.  KS reserves the right to refuse or cancel any such orders whether or not the order has been confirmed and your credit card charged.  If your credit card has already been charged for the purchase and your order is cancelled, KS shall issue a credit to your credit card account in the amount of the incorrect price.<br/><br/>Certain state laws do not allow limitations on implied warranties or the exclusion or limitation of certain damages.  If these laws apply to you, some or all of the above disclaimers, exclusions, or limitations may not apply to you, and you might have additional rights.</p>
   <h6>Purchases of Products From KS</h6>
   <p>It is important that you understand the following regarding any produces you purchase from me:<br/>
(1) I have a financial interest in the products I may offer for sale to you; <br/>
(2) You have several alternative options to purchase any products I offer to you, including online or local retail outlets.  I will be happy to assist you to find an alternative purchasing outlet if you so desire; <br/>
(3) You have the option to use one of the alternatives listed above rather than to purchase a product from me; and <br/>
(4) I assure you that you will not be treated differently by me if you choose one of the alternatives above.</p>
<h4>7. Indemnification</h4>
<p>You agree to defend, indemnify, and hold harmless KS, her affiliates, contractors, and partners of any and all type, and all of their respective directors, officers, employees, representatives, proprietors, partners, shareholders, servants, principals, agents, predecessors, successors, assigns, accountants, and attorneys from and against any and all suits, actions, claims, proceedings, damages, settlements, judgments, injuries, liabilities, obligations, losses, risks, costs, and expenses (including without limitation attorneys' fees and costs) relating to or arising from this Site, your use of this Site, your Submission(s) to the Site, your fraud, violation of law, or willful misconduct, and any breach by you of these Terms and Conditions.</p>
<h4>8. Corrections and Changes</h4>
<p>KS endeavors to keep the Site and Site Materials on, in, and through this Site up-to-date.  Without limiting anything else in these Terms and Conditions or otherwise, KS is not responsible for any errors or omissions in the Site or Site Materials.  KS may make changes to the Site or Site Materials, or to the products, information, or services made available in connection with this Site, at any time with or without notice, and KS makes no commitment to update the information contained on or in this Site.  KS reserves the right to terminate your access to this Site in the event that you violate these Terms and Conditions or for any reason whatever, or for no reason, with or without notice, in addition to any and all other remedies available at law or in equity.</p>
<h4>9. Links to Other Web Sites</h4>
<p>This Site may, from time to time, contain links to other third-party internet web sites for the convenience of users in locating information, products, or services that may be of interest.  KS is not responsible for examining or evaluating, and KS does not warrant the offerings of, any of these businesses or individuals or the content of their web sites.  These sites are maintained by organizations over which KS exercises no control, and KS expressly disclaims any and all responsibility for the content, the accuracy of the information, the security of information provided to any third-party sites, and the quality of products or services provided by or advertised on these third-party sites.</p>
   <p>Without limiting anything else in these Terms and Conditions or otherwise, KS does not assume any responsibility or liability for any errors or omissions in the Site or Site Materials, or for the information, links, text, graphics, or other items made available on other web sites created, maintained, or otherwise controlled by third parties.  You should carefully review the privacy statements and other conditions of use for any third-party material.</p>
   <h4>10. Governing Law, Jurisdiction, and Disputes</h4>
   <h5>GOVERNING LAW </h5>
   <p>By visiting the Site, you agree that the laws of the state of Washington, without regard to principles of conflict of laws, will exclusively govern these Terms and Conditions and any dispute of any sort that might arise between you and KS. </p>
   <h5>JURISDICTION</h5>
   <p>By accessing, viewing, or using the works, content, or materials on this Site, you consent to the exclusive jurisdiction of the federal and state courts presiding in King County, Washington, and agree to accept service of process by personal delivery or mail and hereby waive any and all jurisdictional and venue defenses otherwise available.  Any party who unsuccessfully challenges the enforceability of this jurisdiction clause shall reimburse the prevailing party for its attorney's fees and costs, and the party prevailing in any such dispute shall be awarded its attorneys' fees and costs.<br/><br/>This Site is controlled and operated by KS from her offices within the United States and the State of Washington.  Without limiting anything else, KS makes no representation that the works, content, materials, services, information, or products available on, in, or through the Site are appropriate or available for use in other locations, and access to them from territories where they are illegal, regulated, or otherwise limited, is prohibited.  Those who choose to access this Site from other locations do so of their own free will and are responsible for compliance with all applicable laws.  The waiver or failure of KS to exercise in any respect any right provided hereunder shall not be deemed a waiver of such right in the future or a waiver of any of the other rights established under these Terms and Conditions. </p>
   <h5>DISPUTES</h5>
   <p>These Terms and Conditions, including, without limitation, the Privacy Statement, represent the entire agreement between you and KS with respect to the subject matter hereof, and supersede any and all prior and contemporaneous written and oral representations, understandings, and agreements, express and implied, and will be governed by and construed in accordance with the laws of the State of Washington, without regard to principles of conflict of laws.<br/><br/>Any dispute relating in any way to your visit to the Site or to products or services sold, distributed, or provided, by KS or through the Site shall be adjudicated in any state or federal court in King County, Washington, and you consent to exclusive jurisdiction and venue in such courts.</p>
   <h4>11. Force Majeure</h4>
   <p>KS shall not be liable for any damages resulting from a failure or delay in performance caused by causes beyond KS’s reasonable control and occurring without her fault or negligence, including, without limitation, failure of suppliers, subcontractors, and carriers.  Without limiting anything else in these Terms and Conditions or otherwise, neither KS, her affiliates, contractors, and partners of any and all type, nor all of their respective directors, officers, employees, representatives, proprietors, partners, shareholders, servants, principals, agents, predecessors, successors, assigns, accountants, and attorneys will be liable for any loss resulting from failure of electronic or mechanical equipment or communication lines, telephone or other interconnection problems or errors, computer viruses, unauthorized access, theft, operator errors, severe weather, earthquakes, natural disasters, strikes or other labor problems, wars, armed conflict or governmental restrictions.</p>
   <h4>12. Your Account </h4>
   <p>If you use this Site, you are responsible for maintaining the confidentiality of your private information, including your private health information, for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password, if any.  KS does provide products or services directly to Children.  If you are under 13, you may use katelstewart.com only with the involvement of a parent or guardian.  KS reserves the right to refuse service, terminate accounts, remove or edit content, or cancel access in her sole discretion.</p>
   <h4>13.  Risk of Loss</h4>
   <p>All items purchased from KS are made pursuant to a shipment contract.  This means that the risk of loss and title for such items pass to you upon KS’s delivery to the carrier.</p>
   <h4>14.  Site Policies, Modifications, and Severability</h4>
   <p>KS reserves the right to make changes to the Site, policies, and these Terms and Conditions at any time.  If any of these conditions shall be deemed invalid, void, or for any reason unenforceable, that condition shall be deemed severable and shall not affect the validity and enforceability of any remaining condition.  Headings used in these Terms and Conditions are for reference only and shall not affect the interpretation of these Terms and Conditions.</p>
   <h4>15.  Copyright Complaints </h4>
   <p>KS respects the intellectual property of others.  If you believe that your work has been copied in a way that constitutes copyright infringement, please provide KS’s copyright agent the written information specified below.  Please note that this procedure is exclusively for notifying KS that your copyrighted material has been infringed. </p>
   
   <ul>
   <li>  An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;</li> 
    <li> A specific description of the copyrighted work that you claim has been infringed upon;</li>
    <li> A specific description of where the material that you claim is infringing is located on the Site;</li> 
   <li>  Your address, telephone number, and e-mail address;</li>
   <li>  A statement by you that you have a good-faith belief that the disputed use is not authorized or allowed by the copyright owner, its agent, or the law;</li>
   <li>  A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. </li>
    </ul>
   <p>KS’s Copyright Agent for notice of claims of copyright infringement can be reached as follows:<br/>
Copyright Agent<br/>
2366 Eastlake Ave E.<br/>
#402 Seattle, WA<br/>
98102, USA<br/>

e-mail: info@katelstewart.com</p>
    </div> 





)




}
export default TermsAndCondition
